import "server-only";

import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import { AwsClient } from "aws4fetch";

import { env } from "@/lib/env";
import { createLogger } from "@/lib/logger";

const logger = createLogger("media");

/**
 * Where product photos live. Both frontends (Vercel and Railway) must see
 * the same files, so production uses an S3-compatible bucket (Cloudflare
 * R2): uploads go through the S3 API, visitors load them from the bucket's
 * public URL. "local" keeps them in a folder, served by /media/[...key];
 * only for development.
 */
export type MediaStorage = {
    put(key: string, body: Uint8Array, contentType: string): Promise<void>;
    remove(key: string): Promise<void>;
    /** Public URL stored on the image record. */
    urlFor(key: string): string;
    /** The key of a URL this storage issued, or null (e.g. seeded images in /public). */
    keyFor(url: string): string | null;
};

export class MediaStorageError extends Error {
    constructor(message: string, options?: ErrorOptions) {
        super(message, options);
        this.name = "MediaStorageError";
    }
}

/** Keys are generated by the app: products/<id>/<random>.<ext>. */
export const MEDIA_KEY_PATTERN = /^products\/[a-z0-9-]{1,64}\/[a-z0-9-]{8,64}\.(jpg|png|webp|avif)$/i;

const LOCAL_URL_PREFIX = "/media/";
const S3_TIMEOUT_MS = 15_000;
const IMMUTABLE = "public, max-age=31536000, immutable";

function keyFromUrl(url: string, prefix: string) {
    if (!url.startsWith(prefix)) return null;

    const key = url.slice(prefix.length);
    return MEDIA_KEY_PATTERN.test(key) ? key : null;
}

export function localMediaPath(key: string) {
    if (!MEDIA_KEY_PATTERN.test(key)) {
        throw new MediaStorageError("Invalid media key");
    }

    return path.resolve(env.MEDIA_LOCAL_DIR, key);
}

const localStorage: MediaStorage = {
    async put(key, body) {
        const file = localMediaPath(key);
        await mkdir(path.dirname(file), { recursive: true });
        await writeFile(file, body, { flag: "wx" });
    },
    async remove(key) {
        await unlink(localMediaPath(key)).catch((error: NodeJS.ErrnoException) => {
            if (error.code !== "ENOENT") throw error;
        });
    },
    urlFor: (key) => LOCAL_URL_PREFIX + key,
    keyFor: (url) => keyFromUrl(url, LOCAL_URL_PREFIX),
};

export async function readLocalMedia(key: string) {
    return readFile(localMediaPath(key));
}

function s3Storage(): MediaStorage {
    const { S3_ENDPOINT, S3_BUCKET, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_REGION, MEDIA_PUBLIC_URL } = env;

    if (!S3_ENDPOINT || !S3_BUCKET || !S3_ACCESS_KEY_ID || !S3_SECRET_ACCESS_KEY || !MEDIA_PUBLIC_URL) {
        throw new MediaStorageError(
            "MEDIA_STORAGE=s3 needs S3_ENDPOINT, S3_BUCKET, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY and MEDIA_PUBLIC_URL",
        );
    }

    const client = new AwsClient({ accessKeyId: S3_ACCESS_KEY_ID, secretAccessKey: S3_SECRET_ACCESS_KEY, region: S3_REGION, service: "s3" });
    const objectUrl = (key: string) => `${S3_ENDPOINT.replace(/\/+$/, "")}/${encodeURIComponent(S3_BUCKET)}/${key}`;

    async function send(method: "PUT" | "DELETE", key: string, init: RequestInit = {}) {
        let response: Response;

        try {
            response = await client.fetch(objectUrl(key), { ...init, method, signal: AbortSignal.timeout(S3_TIMEOUT_MS) });
        } catch (error) {
            throw new MediaStorageError(`S3 ${method} failed`, { cause: error });
        }

        // DELETE of a missing object is a success (204 or 404).
        if (!response.ok && !(method === "DELETE" && response.status === 404)) {
            throw new MediaStorageError(`S3 ${method} returned ${response.status}: ${(await response.text()).slice(0, 200)}`);
        }
    }

    return {
        put: (key, body, contentType) =>
            send("PUT", key, { body: body as BodyInit, headers: { "Content-Type": contentType, "Cache-Control": IMMUTABLE } }),
        remove: (key) => send("DELETE", key),
        urlFor: (key) => `${MEDIA_PUBLIC_URL}/${key}`,
        keyFor: (url) => keyFromUrl(url, `${MEDIA_PUBLIC_URL}/`),
    };
}

let storage: MediaStorage | undefined;

export function getMediaStorage(): MediaStorage {
    if (!storage) {
        if (env.MEDIA_STORAGE === "s3") {
            storage = s3Storage();
        } else {
            if (env.NODE_ENV === "production") {
                logger.warn("MEDIA_STORAGE=local: photos are not shared between instances. Use MEDIA_STORAGE=s3 in production.");
            }
            storage = localStorage;
        }
    }

    return storage;
}

export const mediaCacheControl = IMMUTABLE;
